name = "thesis_code"
uuid = "b58e67be-2946-4239-a229-7f53d260b2e0"
authors = ["Bo Jacobs Strom <bojs.13@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
